import os

class Config:
    SECRET_KEY = os.getenv('FLASK_SECRET_KEY')  
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')  # 
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
    TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
    TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
